version: '4.0'

services:
  reg-service:
    image: student_app_part2:latest
    ports:
      - "8082:8082"
    networks:
      - my_network


  confirmation-service:
    image: student_app_part3:latest
    ports:
      - "8083:8083"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge